version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    target-branch: "1.0.0-rc5"
    commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope"
